language: php

matrix:
  include:
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
  fast_finish: true

services:
  - redis-server

install:
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION $NOTESTS

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - phantomjs --webdriver=8910 > /dev/null &

script:
  - travis/phing-sniff.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - travis/check-sami-parse-errors.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - travis/check-executable-files.sh $DB $TRAVIS_PHP_VERSION $NOTESTS ./
  - sh -c "if [ '$SLOWTESTS' != '1' -a '$DB' = 'mysqli' ]; then phpBB/vendor/bin/phpunit tests/lint_test.php; fi"
  - sh -c "if [ '$NOTESTS' != '1' -a '$SLOWTESTS' != '1' ]; then phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml; fi"
  - sh -c "if [ '$SLOWTESTS' = '1' ]; then phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml --group slow; fi"
  - sh -c "set -x;if [ '$NOTESTS' = '1' -a '$TRAVIS_PULL_REQUEST' != 'false' ]; then git-tools/commit-msg-hook-range.sh origin/$TRAVIS_BRANCH..FETCH_HEAD; fi"
